unique_ids:
  assets:
    standard-page.html: XG6PIQTUJVCDZL3FGOJUZS5RF37B7M35
    theme.css: JWTFKA63KFRH774VR7U2NP6WEY2JBLF3
  forms:
    DashBoard: W74P4LANDSBEUI2CDWB5GWG2VY53RZ6X
    DashBoard.CountryPlot: 5ZIFIKSUODRBW3SWYCJUPNB44A7AJWNB
    DashBoard.GenderAgePlot: 4KHQ4OM5X37FFWGABKZY33QN5R674HTT
    DashBoard.SmallCard: YQNRTTC5MP6JFKIXRQIYY2ICXTKRTE3B
    DashBoard.TimeOfDayPlot: EBAXNAX6X5YHPTF5KRDJLUMAQ3UDDFX5
  modules:
    _plotly_templates: EESO5WTG7JHLJS3C3CUXCI4J66PYDAMH
  scripts: {}
  server_modules:
    ServerModule: 5TTJGRRMWBC77T54PG3GJGOXWUIOTM7M
